opt_dataset:
  fineSize: 256
  augment_fn: base
  use_color: gray
  crop: False
  name: mq
  data_root: /root/autodl-tmp/HE_SN_sample
  source_center: YC,ZD,ZJ
  target_center: TT_Target
  test_center: HB
  P_mask: /root/autodl-tmp/HE_SN_sample/target/raw_patch/10.png
  image_index: 0
  label_index: 1
  num_class: 2

#opt_dataset:
#  fineSize: 256
#  augment_fn: base
#  use_color: gray
#  crop: False
#  name: mq
#  source_dataframe: /g/data/iq24/MQ_sn
#  target_dataframe: /g/data/iq24/MQ_sn
#  test_dataframe: /g/data/iq24/MQ_sn/source
#  train_dataframe: /home/congz3414050/cong/CAGAN_Stain_Norm/data/CAMELYON16/train/train.csv
#  test_output_dir: /home/congz3414050/cong/CAGAN_Stain_Norm/results/visuals
#  P_mask: /g/data/iq24/MQ_sn/target/processed_slide/raw_patches/P_10/10.png
#  image_index: 0
#  label_index: 1
#  num_class: 2


